permissions:
  no-perm: "&cNo permissions!"
  black-market:
    require: true
    node: rs.black-market
  reload:
    require: true
    node: rs.reload
  editor:
    require: true
    node: rs.editor

purchase:
  succeeded:
    message:
      use: true
      text: "&aPurchased!"
    sound:
      use: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
  insufficient:
    message:
      use: true
      message: "&cInsufficient!"
    sound:
      use: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP

# GUI options
# open: item-gui, shop.gui (path to gui config section) or 'next' or 'back' for pages?

shop:
  rotate-time: 6h
  item-format:
    name: "%name%"
    lore:
      - "&7Price: &a%formatted-price% %price%" # %price%, %formatted-price%
      - "&8-> &aLeft click to purchase"
  gui:
    # todo: locked to only have one type in inventory
    items: 12,13,14
    name: "Rotating Shop"
    rows: 3
    1,3,5,7,9,11,13,15,17,19,21,23,25:
      name: " "
      type: RED_STAINED_GLASS_PANE
    0,2,4,6,8,10,12,14,16,18,20,22,24,26:
      name: " "
      type: BLACK_STAINED_GLASS_PANE
    22:
      name: "&#A900FFꜱ&#9C0DFFʜ&#8F1AFFᴀ&#8228FFʀ&#7535FFᴅ&#6842FFꜱ &#4E5DFFʙ&#416AFFᴀ&#3477FFʟ&#2784FFᴀ&#1A92FFɴ&#0D9FFFᴄ&#00ACFFᴇ"
      glowing: true
      type: PRISMARINE_SHARD
    26:
      name: "&#FF0000ᴛɪᴍᴇ ʟᴇꜰᴛ"
      glowing: true
      lore:
        - "&b%time-left%" # todo: variable updates per second?
      type: WRITABLE_BOOK
    18:
      name: "&#FF005Dɪ&#F8006Fᴛ&#F10081ᴇ&#E90093ᴍ&#E200A5ꜱ &#D400C9ʟ&#CC00DBɪ&#C500EDꜱ&#BE00FFᴛ"
      type: BARRIER
      open: items-gui
      permission_1:
        node: op
        name: "&#FF005Dᴀ&#F9006Dᴅ&#F2007Dᴍ&#EC008Eɪ&#E5009Eɴ &#D800BEᴘ&#D200CEᴀ&#CB00DFɴ&#C500EFᴇ&#BE00FFʟ"
        glowing: true
        type: BARRIER

items-gui: # Items are filed from top to bottom so any empty slots will contain an item
  # todo: have a background item?
  # todo: do we dupe the item?
  name: "ꜱʜᴏᴘ ɪᴛᴇᴍꜱ"
  rows: 6
  45:
    type: ARROW
    name: "&#FF0000ʙᴀᴄᴋ"
    open: back
    #lore:
    #  - ""
  53:
    type: ARROW
    name: "&#08FB2Cɴᴇxᴛ"
    open: next
    #lore:
    #  - ""
  46,47,48,49,50,51,52:
    name: " "
    type: BLACK_STAINED_GLASS_PANE
  #LIGHT_GRAY_STAINED_GLASS_PANE:
    #name: " "
    #slots:
