permissions:
  reload: rotatingshop.reload
  editor: rotatingshop.editor
  no-permission:
    use: true
    message: "&cNo permissions!"

purchase:
  succeeded:
    message:
      use: true
      text: "&aPurchased!"
    sound:
      use: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
  insufficient:
    message:
      use: true
      message: "&cInsufficient!"
    sound:
      use: true
      sound: ENTITY_EXPERIENCE_ORB_PICKUP

shop:
  rotate-time: 6h
  item-format:
    name: "%name%"
    lore:
      - "&7Price: &a%formatted-price% %price%" # %price%, %formatted-price%
      - "&8-> &aLeft click to purchase"
  gui:
    name: "Rotating Shop"
    items: 12,13,14
    rows: 3
    RED_STAINED_GLASS_PANE:
      name: " "
      slots: 1,3,5,7,9,11,13,15,17,19,21,23,25
    BLACK_STAINED_GLASS_PANE:
      name: " "
      glowing: true # todo: test
      slots: 0,2,4,6,8,10,12,14,16,18,20,22,24,26
    WRITABLE_BOOK:
      name: "&#FF0000ᴛɪᴍᴇ ʟᴇꜰᴛ: %time-left%"
      lore:
        - "&b%time-left%" # todo: variable updates per second?
    BARRIER:
      permission_1:
        node: op
        name: ""
        slots: 18
      permission_2:
        node: something.else
        name: ""
        slots: 18

items-gui: # Items are filed from top to bottom so any empty slots will contain an item
  # todo: have a background item?
  # todo: do we dupe the item?
  next:
    type: ARROW
    name: ""
    lore:
      - ""
  back:
    type: ARROW
    name: ""
    lore:
      - ""
  BLACK_STAINED_GLASS_PANE:
    name: " "
    slots: 44,45,46,47,48,49,50,51,52
  #LIGHT_GRAY_STAINED_GLASS_PANE:
    #name: " "
    #slots:
