name: RotatingShop
version: 1.0
main: me.jakepronger.rotatingshop.RotatingShop
description: RotatingShop plugin for HeartbeatMC
api-version: 1.21
depend: [PlayerPoints]
author: jakepronger
commands:
  blackmarket:
    aliases: bm
    description: something